Initialize database and created models and constants
CreamDubaiMonkeys/EventOrganizer pull request #6
Opened 2024-08-23 14:07 UTC by adamifnou

Please review the Event.java line 35 where we used java.sql.Date instead of java.util.Date

2024-08-23 17:03 UTC, Qouentinne requested changes
C'est cool, les tables sont bien créées au lancement, cette partie fonctionne bien 👌
Je vous laisse pas mal de commentaires mais y'a des choses rapides à checker.
Il manque les getters et setters 😊
D'un point de vue lisibilité en db, je me pose la questions des Enum : à chaque fois qu'on en utilise un, on enregistre un nombre en db sans possibilité de se reporter à sa signification.
Est-ce qu'il ne faudrait pas créer des "tables Enum" ? Genre une table event_status avec un id et un nom et on mettrait l'id dans le user_event ?

2024-08-23 17:03 UTC, Qouentinne commented on EventOrganizerBack/src/main/java/com/example/EventOrganizerBack/model/Comment.java
> +    private String content;
En db, c'est un VARCHAR(255), y'a pas un paramétrage pour l'avoir en TEXT ?

2024-08-23 17:03 UTC, Qouentinne commented on EventOrganizerBack/src/main/java/com/example/EventOrganizerBack/model/Event.java
> +    private Time time; // used java.sql.Time
Vu, on le garde pour le moment, on verra si ça fait le job

2024-08-23 17:03 UTC, Qouentinne commented on EventOrganizerBack/src/main/java/com/example/EventOrganizerBack/model/Event.java
> +    private String description;
La même ici, on va avoir besoin de TEXT en db

2024-08-23 17:03 UTC, Qouentinne commented on EventOrganizerBack/src/main/java/com/example/EventOrganizerBack/model/NotificationUser.java
> +
Il manque le is_read boolean sur ce modèle

2024-08-23 17:03 UTC, Qouentinne commented on EventOrganizerBack/src/main/java/com/example/EventOrganizerBack/model/Comment.java
> +    @ManyToOne
Est-ce que vous avez fait quelques tests en sql pour écrire en db et faire des select avec jointures pour voir si ça s'est bien mis en place ?

2024-08-24 09:51 UTC, adamifnou commented on EventOrganizerBack/src/main/java/com/example/EventOrganizerBack/model/Comment.java
> +    private String content;
yes, c'est @Lob

2024-08-24 09:51 UTC, adamifnou commented on EventOrganizerBack/src/main/java/com/example/EventOrganizerBack/model/NotificationUser.java
> +
YESS Added

2024-08-24 09:53 UTC, adamifnou commented on EventOrganizerBack/src/main/java/com/example/EventOrganizerBack/model/Comment.java
> +    @ManyToOne
Ok je test et je revient avec le résultat

2024-08-26 07:43 UTC, Qouentinne approved these changes

2024-08-26 07:43 UTC, merged

2024-08-26 07:43 UTC, ZBRania approved these changes