setup basic spring security config
CreamDubaiMonkeys/EventOrganizer pull request #7
Opened 2024-08-23 14:29 UTC by Qouentinne

Setup security config so that everybody has access to the whole API

2024-08-25 12:54 UTC, adamifnou requested changes
The file structure is not like the one in main branch, it need to be conformed to main 

![image](https://github.com/user-attachments/assets/c3c10c3a-acc5-4ca5-a4d3-b47404b1df62)

2024-08-25 20:28 UTC, Qouentinne commented
v0 working
![Capture d'écran 2024-08-25 222629](https://github.com/user-attachments/assets/5c40f40a-87ca-4079-b207-78638beccb02)

2024-08-26 08:19 UTC, adamifnou approved these changes

2024-08-26 08:24 UTC, merged

2024-08-26 08:24 UTC, Laguyzail approved these changes
Bon taff